### ISSUE TITLE
I cannot run it in Centos 7.7.

### ISSUE THREAD

**Issue by datokonoko** [JamesMatchett/AWS-Discord-Bot#17]
I cannot run it in Centos 7.7.
nodejs and awscli are already installed.
The error log is as follows:
Unexpected string in JSON at position 321
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:672:27)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/DiscordBot/src/Bot.js:5:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

**Comment by JamesMatchett** [comment]
Hi @CydiaHiko ,

I'm really sorry to hear that, did you setup the config.json file as per the readme? 

The line the error is thrown on according to your error log is 

`const { ACCESSKEY } = require('../config.json');` which makes me think it could potentially be an issue with your config.json file, please let me know if I'm wrong.

Whatever the issue in your JSON is, it's possibly at the 321st position according to the error log.

Looking forward to hearing from you :) - J

**Comment by datokonoko** [comment]
Thank you for your reply.

I think I did as described, but if there are any mistakes, please let me know.

{
"BOT_TOKEN": "8**************q",
"ROLEID": "630689062155714560",
"CHANNELID": "6**************8",
"ACCESSKEY": "A**************4",
"SECRETKEY": "4**************m",
"SESSIONTOKEN": "*Insert the AWS session token here (may not be needed)*",
"INSTANCE": "i-**************"
"MESSAGELOGGING": "F" (or leave as 'T' if you want specific error messages logged to the Discord channel which may contain sensitive info like keys or instance IDs)
}

**Comment by datokonoko** [comment]
hide secret keys.

**Comment by JamesMatchett** [comment]
Hi @CydiaHiko if you remove 

"(or leave as 'T' if you want specific error messages logged to the Discord channel which may contain sensitive info like keys or instance IDs)"

It should hopefully work for you, that bit is just a comment explaining what the flag is for.

Hope this helps :)

**Comment by datokonoko** [comment]
So like this?
{
"BOT_TOKEN": "8-----------------q",
"ROLEID": "6-------------0",
"CHANNELID": "630690371596320788",
"ACCESSKEY": "A----------------------4",
"SECRETKEY": "4-------------------m",
"SESSIONTOKEN": "",
"INSTANCE": "i-0-------------------9"
"MESSAGELOGGING": ""
}

**Comment by JamesMatchett** [comment]
Very close, more like:


{
"BOT_TOKEN": "8-----------------q",
"ROLEID": "6-------------0",
"CHANNELID": "630690371596320788",
"ACCESSKEY": "A----------------------4",
"SECRETKEY": "4-------------------m",
"SESSIONTOKEN": "",
"INSTANCE": "i-0-------------------9"
"MESSAGELOGGING": "F"
}

**Comment by datokonoko** [comment]
still not working...

**Comment by JamesMatchett** [comment]
No worries, are you getting a different error log? 

if so, what error log are you getting? :)

**Comment by datokonoko** [comment]
maybe this one

yntaxError: /root/DiscordBot/config.json: Unexpected string in JSON at position 259
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:961:27)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/DiscordBot/src/Bot.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)

**Comment by JamesMatchett** [comment]
Really sorry to hear this, if you can attach your config.json @CydiaHiko **with the keys and sensitive information redacted** and I'll give it a test to see if I can find any issues.

**Comment by datokonoko** [comment]
Does this program work with Linux?
Should I send the secret key without concealing it?

**Comment by datokonoko** [comment]
Does this program work with Linux?
Should I send the secret key without concealing it?

**Comment by JamesMatchett** [comment]
The program definitely should work with Linux, and please do conceal all of your secret keys, but try to maintain the structure of the JSON as that will really help me figure out why it isn't working.

Thank you - J

**Comment by datokonoko** [comment]
{
"BOT_TOKEN": "*--------------------*",
"ROLEID": "*--------------------*",
"CHANNELID": "*--------------------*",
"ACCESSKEY": "*--------------------*",
"SECRETKEY": "*--------------------*",
"SESSIONTOKEN": "*Insert the AWS session token here (may not be needed)*",
"INSTANCE": "*--------------------*"
"MESSAGELOGGING": "T" (or leave as 'T' if you want specific error messages logged to the Discord channel which may contain sensitive info like keys or instance IDs)
}

**Comment by JamesMatchett** [comment]
hey, you need to remove the comment after the "T" on MESSAGELOGGING, you should remove:
 
(or leave as 'T' if you want specific error messages logged to the Discord channel which may contain sensitive info like keys or instance IDs)

So your Config should look like this:

{
"BOT_TOKEN": "--------------------",
"ROLEID": "--------------------",
"CHANNELID": "--------------------",
"ACCESSKEY": "--------------------",
"SECRETKEY": "--------------------",
"SESSIONTOKEN": "Insert the AWS session token here (may not be needed)",
"INSTANCE": "--------------------"
"MESSAGELOGGING": "T"
}

**Comment by datokonoko** [comment]
There is still an error.

yntaxError: /root/DiscordBot/config.json: Unexpected string in JSON at position 321
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:961:27)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/DiscordBot/src/Bot.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)

**Comment by JamesMatchett** [comment]
{
"BOT_TOKEN":"",
"ROLEID":"",
"CHANNELID":"",
"ACCESSKEY":"",
"SECRETKEY":"",
"SESSIONTOKEN":"",
"INSTANCE":"",
"MESSAGELOGGING":"F"
}

**Comment by datokonoko** [comment]
If I input this sentence without editing it, will it work?

**Comment by JamesMatchett** [comment]
it will work once you insert the relevant keys into their respective places. I tested it on my machine just now and it works as it has been working to date. I will definitely have a closer look once I get back home as to why your file isn't working as I was able to recreate your issue with your file

I've removed the explanations around the file to make copying and pasting easier for you

**Comment by CydiaHiko** [comment]
Oh I got different error.

Error: Invalid token: 8fB7SMacRB0PvcJqjhi4iioT6LdL3L3q
    at WebSocket.ws.onclose (/root/DiscordBot/node_modules/eris/lib/gateway/Shard.js:1628:40)
    at WebSocket.onClose (/root/DiscordBot/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:209:13)
    at WebSocket.emitClose (/root/DiscordBot/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/root/DiscordBot/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at TCP.done (_tls_wrap.js:479:7)

**Comment by datokonoko** [comment]
wait tried again, and it started

**Comment by datokonoko** [comment]
How can I stop this bot?

**Comment by JamesMatchett** [comment]
you can use the ctrl + z / ctrl + c command to stop the running process or alternatively close the terminal window

**Comment by datokonoko** [comment]
Thank you very much for your support so far.
Thank you.

**Comment by JamesMatchett** [comment]
Glad to hear it's starting! Hoping it's running okay for you :) 

Just a note @CydiaHiko I would delete your most recent error log as it contains a potentially sensitive key

**Comment by JamesMatchett** [comment]
Closing this issue as it appears to be resolved.

Not an issue with code but I could probably clear up my wording and comments in the example config.json, so I'll do that sometime soon.

**Comment by JamesMatchett** [comment]
> {
> "BOT_TOKEN": "_--------------------_",
> "ROLEID": "_--------------------_",
> "CHANNELID": "_--------------------_",
> "ACCESSKEY": "_--------------------_",
> "SECRETKEY": "_--------------------_",
> "SESSIONTOKEN": "_Insert the AWS session token here (may not be needed)_",
> "INSTANCE": "_--------------------_"
> "MESSAGELOGGING": "T" (or leave as 'T' if you want specific error messages logged to the Discord channel which may contain sensitive info like keys or instance IDs)
> }

Hey, just to finish up this issue I couldn't help but not look at it again,

![image](https://user-images.githubusercontent.com/30292929/67146746-fb2b4580-f285-11e9-9457-c16476fa32af.png)

After piping your config.json through hexdump and my config.json found that you were simply missing a comma at the end of the line for "Instance", very small difference but it caused the issue!

**Comment by JamesMatchett** [comment]
> {
> "BOT_TOKEN": "_--------------------_",
> "ROLEID": "_--------------------_",
> "CHANNELID": "_--------------------_",
> "ACCESSKEY": "_--------------------_",
> "SECRETKEY": "_--------------------_",
> "SESSIONTOKEN": "_Insert the AWS session token here (may not be needed)_",
> "INSTANCE": "_--------------------_"
> "MESSAGELOGGING": "T" (or leave as 'T' if you want specific error messages logged to the Discord channel which may contain sensitive info like keys or instance IDs)
> }

Hey, just to finish up this issue I couldn't help but not look at it again,

![image](https://user-images.githubusercontent.com/30292929/67146784-4a717600-f286-11e9-9c4f-31fa3faba8e0.png)


After piping your config.json through hexdump and my config.json found that you were simply missing a comma at the end of the line for "Instance", very small difference but it caused the issue!
