### ISSUE TITLE
$aws status error

### ISSUE THREAD

**Issue by Monkleys** [JamesMatchett/AWS-Discord-Bot#20]
When status is run in discord, the following is returned in discord:

`Error getting status,  TypeError: Cannot read property '0' of undefined`

No difference if instance is running or not. Confirmed start and stop is working as expected.

Console error:
```TypeError: Cannot read property '0' of undefined
    at /home/ubuntu/AWS-Discord-Bot/DiscordBot/src/Bot.js:86:105
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by Monkleys** [comment]
For anyone encountering this issue, here's the fix:

This [line](https://github.com/JamesMatchett/AWS-Discord-Bot/blob/master/DiscordBot/src/Bot.js#L86) assumes that your instance is tagged, so it tries to fetch the first tag. Adding a tag to your instance fixes the issue.
